# Hawk Eye pipeline configuration.

nodes:
  -
    type: computed
    name: rayMarch
    final: true
    input:
    output:
        color:
            access: w
            format: color-optimal
    shaders:
        compute: ../../src/Shaders/march.comp.glsl
    uniforms:
      -
        name: camera
        type: uniform
        size: 64
